package jnibwapi.types;

/**
 * Represents a StarCraft explosion type.
 * 
 * For a description of fields see: http://code.google.com/p/bwapi/wiki/Order
 */
public class OrderType {
	public static final int numAttributes = 1;
	
	private String name = null;
	private int ID = 0;
	
	public enum OrderTypeTypes {
		Die,
		Stop,
		Guard,
		PlayerGuard,
		TurretGuard,
		BunkerGuard,
		Move,
		Undefined7,
		Undefined8,
		Undefined9,
		AttackUnit,
		Undefined11,
		AttackTile,
		Hover,
		AttackMove,
		InfestedCommandCenter,
		UnusedNothing,
		UnusedPowerup,
		TowerGuard,
		Undefined19,
		VultureMine,
		Undefined21,
		Undefined22,
		Nothing,
		Nothing3,
		Undefined25,
		Undefined26,
		CastInfestation,
		Undefined28,
		InfestingCommandCenter,
		PlaceBuilding,
		Undefined31,
		BuildProtoss2,
		ConstructingBuilding,
		Repair,
		Undefined35,
		PlaceAddon,
		BuildAddon,
		Train,
		RallyPointUnit,
		RallyPointTile,
		ZergBirth,
		ZergUnitMorph,
		ZergBuildingMorph,
		IncompleteBuilding,
		Undefined45,
		BuildNydusExit,
		EnterNydusCanal,
		Undefined48,
		Follow,
		Carrier,
		ReaverCarrierMove,
		Undefined52,
		Undefined53,
		Undefined54,
		CarrierIgnore2,
		Undefined56,
		Undefined57,
		Reaver,
		Undefined59,
		Undefined60,
		Undefined61,
		Undefined62,
		TrainFighter,
		InterceptorAttack,
		ScarabAttack,
		RechargeShieldsUnit,
		RechargeShieldsBattery,
		ShieldBattery,
		InterceptorReturn,
		Undefined70,
		BuildingLand,
		BuildingLiftOff,
		DroneLiftOff,
		LiftingOff,
		ResearchTech,
		Upgrade,
		Larva,
		SpawningLarva,
		Harvest1,
		Harvest2,
		MoveToGas, // - Unit is moving to refinery
		WaitForGas, // - Unit is waiting to enter the refinery (another unit is currently in it)
		HarvestGas, // - Unit is in refinery
		ReturnGas, // - Unit is returning gas to center
		MoveToMinerals, // - Unit is moving to mineral patch
		WaitForMinerals, // - Unit is waiting to use the mineral patch (another unit is currently
							// mining from it)
		MiningMinerals, // - Unit is mining minerals from mineral patch
		Harvest3,
		Harvest4,
		ReturnMinerals, // - Unit is returning minerals to center
		Interrupted,
		EnterTransport,
		PickupIdle,
		PickupTransport,
		PickupBunker,
		Pickup4,
		PowerupIdle,
		Sieging,
		Unsieging,
		Undefined100,
		InitCreepGrowth,
		SpreadCreep,
		StoppingCreepGrowth,
		GuardianAspect,
		ArchonWarp,
		CompletingArchonsummon,
		HoldPosition,
		Undefined108,
		Cloak,
		Decloak,
		Unload,
		MoveUnload,
		FireYamatoGun,
		Undefined114,
		CastLockdown,
		Burrowing,
		Burrowed,
		Unburrowing,
		CastDarkSwarm,
		CastParasite,
		CastSpawnBroodlings,
		CastEMPShockwave,
		NukeWait,
		NukeTrain,
		NukeLaunch,
		NukePaint,
		NukeUnit,
		CastNuclearStrike,
		NukeTrack,
		Undefined130,
		CloakNearbyUnits,
		PlaceMine,
		RightClickAction,
		Undefined134,
		Undefined135,
		Undefined136,
		CastRecall,
		TeleporttoLocation,
		CastScannerSweep,
		Scanner,
		CastDefensiveMatrix,
		CastPsionicStorm,
		CastIrradiate,
		CastPlague,
		CastConsume,
		CastEnsnare,
		CastStasisField,
		CastHallucination,
		Hallucination2,
		ResetCollision,
		Undefined151,
		Patrol,
		CTFCOPInit,
		CTFCOP1,
		CTFCOP2,
		ComputerAI,
		AtkMoveEP,
		HarassMove,
		AIPatrol,
		GuardPost,
		RescuePassive,
		Neutral,
		ComputerReturn,
		Undefined164,
		SelfDestrucing,
		Critter,
		HiddenGun,
		OpenDoor,
		CloseDoor,
		HideTrap,
		RevealTrap,
		Enabledoodad,
		Disabledoodad,
		Warpin,
		Medic,
		MedicHeal1,
		HealMove,
		Undefined178,
		MedicHeal2,
		CastRestoration,
		CastDisruptionWeb,
		CastMindControl,
		DarkArchonMeld,
		CastFeedback,
		CastOpticalFlare,
		CastMaelstrom,
		JunkYardDog,
		Fatal,
		None,
		Unknown
	};
	
	public OrderType(int[] data, int index) {
		ID = data[index++];
	}
	
	public String getName() {
		return name;
	}
	
	public void setName(String name) {
		this.name = name;
	}
	
	public int getID() {
		return ID;
	}
}
